### ISSUE TITLE
outdated information?

### ISSUE THREAD

**Issue by hasenj** [schacon/whygitisbetter#3]
- `hg` _does_ have a github/gitorious equivelant: bitbucket
- some people claim that `hg` _does_ have cheap branches (I can't verify this since I don't use it) (I also lost the link to the claim).

**Comment by sesam** [comment]
hg and bitbucket is also mentioned in the other open Issue. schacon and chchris6 got a pull request to cover the hg/bitbucket issue.
After looking closer, schacon has actually once changed+reverted in that topic, and then said that the github topic/reason will stay as is until some other site get as big and as social-focused as github.

**Comment by dak180** [comment]
On the subject of cheap branches I would recommend looking at [A Guide to Branching in Mercurial](http://stevelosh.com/blog/2009/08/a-guide-to-branching-in-mercurial/), which makes a excellent case for `hg` actually having cheaper branching than `git`.

Also on "The Staging Area" I would recommend reading [A Git User's Guide to Mercurial Queues](http://stevelosh.com/blog/2010/08/a-git-users-guide-to-mercurial-queues/) which, I think, demonstrates that `hg` does in fact have an equivalent, just one one that is opt-in rather than opt-out.

**Comment by tjdett** [comment]
While most Mercurial documentation on branching doesn't normally start with bookmarks for legacy reasons, including "better than Hg" under "Cheap Local Branching" seems increasingly out-of-date.

Since Mercurial 1.8, bookmarks are core functionality which doesn't need to be enabled. Pushes with `-B` transfer both the changesets and the bookmark. The only remaining annoyance is that password-protected servers will prompt for the password twice - once for the changesets, and again for the bookmark.

It's a minor point, but given this site is the second Google hit for "git vs hg", it's probably worth amending the text.

**Comment by sesam** [comment]
In Feb. 2010 I submitted some patches. It has still not appeared on the website though. For instance the Swedish page is still half-ass translated and my 100% complete translation hasn't been put up.
The maintainers of http://whygitisbetterthanx.com/ and http://sv.whygitisbetterthanx.com/ simply have stopped spending any time on the project :( :(.

**Comment by Burgestrand** [comment]
Yeah, issue #1 still discusses this as well dating back to 24th of April 2009.

**Comment by Mange** [comment]
@sesam: I did the whole Swedish translation. Only half was pulled and he stopped responding to me as well. Please don't attribute the lack of response to me. I finally deleted my fork due to the lack of interest.

**Comment by sesam** [comment]
@Mange: great work, you did :). Of service to future internets, I hope it will be :).
I think I found two or three Swedish translations last year and merged them together, so perhaps your work hasn't been lost yet -- I haven't deleted my fork :)
